######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 20 15:34:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
QT += opengl
HEADERS += qixwidget.h qixwindow.h
SOURCES += main.cpp qixwidget.cpp qixwindow.cpp
RESOURCES += qix.qrc
